version: '3'
services:

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - plus-s-api
      - db
    restart: always
    environment:
      DOMAINS: 'api4.plus-s.com.ar -> http://plus-s-api:8000'
      STAGE: 'production' # Don't use production until staging works
      FORCE_RENEW: 'true'

  plus-s-api:
    image: ghcr.io/plus-s/back-end-prod:latest
    command: python manage.py runserver plus-s-api:8000
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=${PROD_DB_NAME}
      - POSTGRES_USER=${PROD_DB_USER}
      - POSTGRES_PASSWORD=${PROD_DB_PASSWORD}
      - POSTGRES_HOST=${PROD_DB_HOST}
